### ISSUE TITLE
sentencepiece tokenizer unexpected behaviour

### ISSUE THREAD

**Issue by abuelnasr0** [keras-team/keras-nlp#1036]
when passing an `id` that is out of the vocabulary to the `SentencePieceTokenizer.id_to_token( id )`. the whole notebook crashes. I never experienced something like this. I tried it locally and at google colab and the notebook crashed in both.
I don't know if there will be any situation where the user will pass an `id` which is out of the vocabulary to a `SentencePieceTokenizer`. should we but that into consideration? if yes, it would be easy to return a value error for example.

**Comment by abuelnasr0** [comment]
here is a colab example:
https://colab.research.google.com/drive/1Xl9Twdabj1WulLpboaRa7vngWBmxyi0a?usp=sharing

**Comment by jbischof** [comment]
@abuelnasr0 the problem is that the vocabulary is zero indexed. The last valid index with a vocab of size `8` is `7`. I was able to access all of the vocab with `token_to_id` in my [gist](https://colab.sandbox.google.com/gist/jbischof/c5de3ec9fe2c827257cb7b891c4d29a7/sentencepiece-crash-example.ipynb).

However, crashing without an error message is a bad user experience. @mattdangerw what do you think of catching such errors inside `token_to_id`? Is this just a problem with the `sentencepiece` library or others as well?

**Comment by abuelnasr0** [comment]
@jbischof 
this method is implemented in WordPieceTokenizer and BytePairTokenizer.
for WordPieceTokenizer, it will return a python error (list index out of range).
for BytePairTokenizer, it will return None.
I think it's a problem in `sentencepiece` library.
