### ISSUE TITLE
`load_weights=False` still downloads the weights

### ISSUE THREAD

**Issue by Philmod** [keras-team/keras-nlp#1154]
When using `load_weights=False`, I'm expecting the weights _not_ to be downloaded (like for `keras-cv`) but they are being downloaded.

Full example: 

```
classifier = keras_nlp.models.BertClassifier.from_preset(
  'bert_tiny_en_uncased',
  load_weights=False
)
```

**Comment by abheesht17** [comment]
@Philmod - I do not see the weights being downloaded. See this: https://colab.research.google.com/drive/1iD_BAte8uU8hZff1YUPH2IJvKbPudBaZ?usp=sharing.

The vocabulary file is being downloaded because the preset preprocessor is used. The model weights are not being downloaded. If you want to avoid the vocabulary from being downloaded, you can pass your own preprocessor to `from_preset`.

**Comment by abheesht17** [comment]
Also, super-awesome that we'll have KerasNLP installed by default on Kaggle! :)

**Comment by jbischof** [comment]
@Philmod see #1050 for a full example of this

**Comment by Philmod** [comment]
Thank y'all!
