### ISSUE TITLE
Help us test out multi-backend KerasNLP

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#1176]
As we are getting a lot of contributor interest, opening this sticky issue for the main place we would love contributor help right now.

KerasNLP recently re-released with multi-backend support on top of [Keras Core](https://keras.io/keras_core/).

We would love help finding bugs and improving our experience here. Try writing multi-backend KerasNLP workflows, or specific torch, jax and tf training jobs. Tell us what breaks, what is unclear, etc.

Please open issue for any bugs.

**Comment by riskyhomo** [comment]
Hello iam very much interested in contributing to kerasNLP please guide me how to familiarise with this :)

**Comment by carrycooldude** [comment]
Will love to work on this

**Comment by shivance** [comment]
Hi @riskyhomo !
You could probably go ahead and look around in repo and try the examples out and figure out how KerasNLP is working with multi backend. The code in docstrings is a good place to start as well. 

1. If you find a bug please open a new issue reporting the bug.
2. If you are willing to help us to fix that issue please mention it and open a PR that fixes it!
3. If you are interested in contributing a tutorial which demonstrates usage of kerasNLP please open a feature request issue !

This issue is a starting place to onboard contributors for new multi-backend KerasNLP !

**Comment by chaidosa** [comment]
Hello everyone, I am Pritesh and I'd love to contribute to the ongoing problem.

**Comment by vulkomilev** [comment]
@shivance Can I join to the project ?

**Comment by shivance** [comment]
@vulkomilev Contributions are welcome!
