### ISSUE TITLE
Dependency mismatch for Python 3.11 (no wheel for tensorflow-text)

### ISSUE THREAD

**Issue by bermeitinger-b** [keras-team/keras-nlp#1218]
The [setup.py](https://github.com/keras-team/keras-nlp/blob/bb510bd8e8c15846b7c358ac7d9bc4df02bf743c/setup.py#L81C1-L81C50) lists Python 3.11 as supported.
However, the [requirements.txt](https://github.com/keras-team/keras-nlp/blob/bb510bd8e8c15846b7c358ac7d9bc4df02bf743c/requirements.txt#L3C7-L3C7) shows the dependency `tensorflow-text~=2.13.0`.
But there is [no wheel](https://github.com/tensorflow/text/issues/1175) for the `2.13.x` series, so the installation falls back to `2.12.1` which forces the same tensorflow version (`2.12.1`) and not `2.13.0` as it should be.

From the discussions on https://github.com/tensorflow/text/issues/1175, it seems supporting 3.11 was not intentionally done (?).

**Comment by mattdangerw** [comment]
Thanks for filing! Not sure what issue with 3.11 support for tf.text, but I somewhat doubt it is intentional. I'll follow up with the folks packaging that library.

Note that keras-nlp should not have a strict dependency on 2.13, running with tf 2.12 and tf-text 2.12 is totally fine. But we do want to support 2.13 tf/tf.text with python 3.8–3.11 if possible.

**Comment by mattdangerw** [comment]
Update on this.

1) tensorflow 2.14 and tensorflow-text 2.14 should be out quite soon I think. I believe withing the week.
2) Both are providing wheels for 3.11 it seems (and dropping support for 3.8) -> https://pypi.org/project/tensorflow-text/2.14.0rc0/#files

So I think this will be solved imminently by just upgrading to 2.14.

**Comment by mattdangerw** [comment]
This should be fixed with the latest tf text.
