### ISSUE TITLE
When trying to use BertClassifier in a model I get an error

### ISSUE THREAD

**Issue by eric** [keras-team/keras-nlp#1716]
**Describe the bug**
I have tried to incorporate `BertClassifier` into a model and ran into a strange error:

    ValueError: Cannot get result() since the metric has not yet been built.

**To Reproduce**
https://colab.research.google.com/drive/105441YtXhvcNj4ZnlpS0KpAZILv_CwTb?usp=sharing

**Expected behavior**
I expect it to run without error

**Would you like to help us fix it?**
I've tried to understand how to work around this but so far have been unable to.

**Comment by PythonLearningAccount** [comment]
I have faced a similar problem.
Enabling TF_USE_LEGACY_KERAS solves it.
When you enable this, you need to match the version of tensorflow and tf_keras.
I think this is probably because bert_tiny_en_uncased was created with keras2.
```
!pip install keras-nlp
```
Below the line above, add the following three lines:
```python
!pip install tf_keras==2.17.0
import os
os.environ["TF_USE_LEGACY_KERAS"]="1"
```
I hope this solves your problem.

**Comment by SamanehSaadat** [comment]
Hi @eric!

Could you explain a little bit more about what you're trying to do? Are you trying to use Bert without preprocessing and compiling it with specific loss and metric? Does this [colab](https://colab.research.google.com/drive/1jmn1YgUyZRqy74sFzA_dd8pixyzJN7tB?usp=sharing) do what you're trying to do?
