### ISSUE TITLE
an example with AI4Code competition? 

### ISSUE THREAD

**Issue by Suzan009** [keras-team/keras-nlp#250]
**Is your feature request related to a problem? Please describe.**

There is an on-going different type of nlp competition in kaggle. Can we use keras-nlp to solve this problem? 

https://www.kaggle.com/competitions/AI4Code/

**Comment by chenmoneygithub** [comment]
@Suzan009 Hi! I took a pass over the task, and my understanding is at a high level, this is not very different from text understanding. Basically you want to model the correlation between markdown cells and code cells, but the correlation is represented in "orders" rather than something like a correlation score. 

One thing I have in my mind is if you want to build a BERT-like model, you can use `keras_nlp.layers.TransformerEncoder` to construct the model easily. Do you have something in your mind that you hope KerasNLP could offer? Your opinion is valuable to us, thanks!
