### ISSUE TITLE
Add Notebooks for Examples

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras-nlp#52]
We can add notebooks (or share Colab notebooks) for existing examples in the library (with instructive text and explanation).

**Comment by chenmoneygithub** [comment]
@abheesht17 Thanks for reporting the issue! 

For BERT example it is a bit hard to write the colab for the full pretraining due to the size and complexity of data preprocessing. The machine translation example is basically following [this Keras tutorial](https://keras.io/examples/nlp/neural_machine_translation_with_transformer/), so we may not want a duplicated colab tutorial.

But yes, generally if it is doable, we will write colab for our example.

**Comment by chenmoneygithub** [comment]
Yea, that one would be nice to add!

**Comment by abheesht17** [comment]
Sure 👍🏼

**Comment by abheesht17** [comment]
@mattdangerw, I reckon this issue can be closed since we have examples on keras.io; I guess we don't really need notebooks here?

**Comment by shivance** [comment]
@abheesht17, I think this issue should be converted to Kaggle wishlist. While keras-io can still be the place for it, I think it's much more meaningful to add examples to Kaggle !

#726

**Comment by shivance** [comment]
Hi @giuliocn, I can totally understand the position you are in. We are working on a lot of Task specific tutorials, let's hope they get merged soon 🤞🏻 .

You can check [Semantic Similarity Tutorial](https://www.kaggle.com/code/shivanshuman/kerasnlp-semantic-similarity-with-bert) which I created on Kaggle. This will probably help you a lot.

Secondly, a tip which I have personally found always useful, if you want to understand how a particular functionality is to be used, if you are unable to find any tutorial, see **Unit Tests**. Tests are mostly found in a seperate `test` folder or within the same folder as the feature file, with a `test` prefix or suffix to file name.

Good luck !

**Comment by TheAthleticCoder** [comment]
Furthermore, we can perhaps also work towards publishing articles, explanations and tutorials on [Medium](https://medium.com/) or other commonly clicked websites for learning NLP and more. This can allow us to even put the `colab notebooks` to good use since we can display them there for people to see.
