### ISSUE TITLE
Update public roadmap

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras-nlp#574]
We should update our public roadmap to reflex upcoming goals in 2023 and the current state of things with the 0.4 release.

**Comment by ADITYADAS1999** [comment]
hey
  [mattdangerw](https://github.com/mattdangerw) can I work with this docs ?

**Comment by mattdangerw** [comment]
@ADITYADAS1999 I think this one will have to be taken by the direct team, as this will be our roadmap of priorities for the year. But keep an eye out for more Contributions Welcome issues!

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999 I think this one will have to be taken by the direct team, as this will be our roadmap of priorities for the year. But keep an eye out for more Contributions Welcome issues!

thanks [mattdangerw](https://github.com/mattdangerw) for this information, looking forward more friendly issues. 😀

**Comment by chenmoneygithub** [comment]
@mattdangerw Since we are seeing more contributors, shall we prioritize this a bit? I think in general in 2023, we focus on:
1. Generative AI, including pretrained models (decoder-only, seq2seq), samplers and specific tasks.
2. Pretrained models - backbone and task models.
3. Accessible guides and examples on keras.io.
4. Better testing/benchmarking strategy and infrastructure.

Anything I am missing here?

**Comment by ADITYADAS1999** [comment]
> @mattdangerw Since we are seeing more contributors, shall we prioritize this a bit? I think in general in 2023, we focus on:
> 
> 1. Generative AI, including pretrained models (decoder-only, seq2seq), samplers and specific tasks.
> 2. Pretrained models - backbone and task models.
> 3. Accessible guides and examples on keras.io.
> 4. Better testing/benchmarking strategy and infrastructure.
> 
these should be great 😀

Is  there any plan to ship models that can be deployed to a edge device or application ?
