### ISSUE TITLE
Minimum Python Version

### ISSUE THREAD

**Issue by shivance** [keras-team/keras-nlp#773]
KerasNLP currently requires minimum python version as 3.8.

#726 led us to conclusion that direct installation on Kaggle is not possible. We currently use "Hacky git clone import" method to run keras nlp on kaggle (cc : @abheesht17)

This year's [GSoC](https://docs.google.com/document/d/1w7MoOy7FJwECdl3gifPttLN-HnRyWG1kJkTg2g8uKz4/edit) also invites Kaggle tutorials. To make installation experience seamless Why don't we make min python 3.7 (Kaggle is not planning to update it any sooner ( IG ).

**Comment by mattdangerw** [comment]
@sampathweb any thoughts?

I'm not opposed to supporting 3.7 in the pip package. We removed it here https://github.com/keras-team/keras-nlp/pull/590 to keep in step with Tensorflow, but I suppose since our library does support older version of Tensorflow it could make sense to support older versions of python too.

One issue might be testing. We probably don't have the compute right now to be running multiple versions of our tests suite for each python version we want to support.

**Comment by sampathweb** [comment]
Kaggle is planning to update Python to 3.8 hopefully before end of March so we might not want to support 3.7 since its resolved soon.  

Also, TF 2.12 has a minimum requirement of Numpy 1.22.4, which had dropped Python 3.7.  So TF 2.12+ can't support Python 3.7 due to Numpy requirement.

**Comment by mattdangerw** [comment]
@sampathweb thanks for checking this out! Sounds like we can keep our python requirement for now. If kaggle runs into snags and that timeline falls apart we can revisit.
