### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ADITYADAS1999** [keras-team/keras-nlp#786]
In English-to-Spanish translation with KerasNLP  throw an AttributeError: 'numpy.ndarray' object has no attribute 'decode'

https://colab.research.google.com/drive/1jtIRbIt0xqN-yqlfNUwlKAeavg4OO0WT?usp=sharing

![err](https://user-images.githubusercontent.com/58718316/221502741-5a78d412-03e0-40ea-8334-06aa7f3af361.PNG)

cc: @abheesht17

**Comment by abheesht17** [comment]
@ADITYADAS1999, I am not sure what the issue is. The notebook you linked is not the original example notebook, this is the original notebook: https://colab.research.google.com/drive/1OhyqSTo3q5ztjPBA4gmFmVB4lMjm1JDv?usp=sharing. I just ran it now, and it worked fine.

As for the beam search notebook you shared, that error is happening because I modified the `beam_search` util to return all beams. You just have to copy the decoding snippet from this cell (https://colab.research.google.com/drive/1jtIRbIt0xqN-yqlfNUwlKAeavg4OO0WT?usp=sharing#scrollTo=zdKyqn5goO2e) to the last cell...

**Comment by ADITYADAS1999** [comment]
> @ADITYADAS1999, I am not sure what the issue is. The notebook you linked is not the original example notebook, this is the original notebook: https://colab.research.google.com/drive/1OhyqSTo3q5ztjPBA4gmFmVB4lMjm1JDv?usp=sharing. I just ran it now, and it worked fine.
> 
> As for the beam search notebook you shared, that error is happening because I modified the `beam_search` util to return all beams. You just have to copy the decoding snippet from this cell (https://colab.research.google.com/drive/1jtIRbIt0xqN-yqlfNUwlKAeavg4OO0WT?usp=sharing#scrollTo=zdKyqn5goO2e) to the last cell...

thanks @abheesht17 , I will re run the original example now.
