### ISSUE TITLE
XLMRobertaBackbone has no Kernel_initializer defined

### ISSUE THREAD

**Issue by soma2000-lang** [keras-team/keras-nlp#863]
@abheesht17 @mattdangerw I think this needs to be fixed

**Comment by shivance** [comment]
Hi, if you take a look at `XLMRobertaClassifier` , you'll find that we are reusing `roberta_kernel_initializer` in XLMRoberta. 

The reason is simple, XLMRoberta inherits from Roberta. Furthermore, just to be clear, it's just a function that can be implemented seperately for XLMRoberta, and initializes kernel weight with random normal distribution.

**Comment by soma2000-lang** [comment]
@shivance Thanks for clarification.!

**Comment by abheesht17** [comment]
@shivance, thanks for helping out here! :)
